### ISSUE TITLE
Unit test is failing (RTC session ConnectSignalingAndIceCollectionState stops ICE collection ..)

### ISSUE THREAD

**Issue by antimora** [aws/connect-rtc-js#5]
Followed instructions and when I was running the unit tests, I get the follow error:
```
  73 passing (104ms)
  1 failing

  1) RTC session ConnectSignalingAndIceCollectionState stops ICE collection earlier when all candidates are collected for one candidate foudation:
     TypeError: transportSPsList.includes is not a function
      at ConnectSignalingAndIceCollectionState._checkCandidatesSufficient (src/js/rtc_session.js:213:66)
      at ConnectSignalingAndIceCollectionState.onIceCandidate (src/js/rtc_session.js:197:22)
      at Context.<anonymous> (test/unit/rtc_session.js:380:19)



npm ERR! Test failed.  See above for more details.
```

**Comment by yuliangz** [comment]
What is your nodejs version? It might not support https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by antimora** [comment]
It looks like `npm` tool was referencing node version 5.X. I switched to v6.10.3 using `n` command line tool.  You can close this ticket.
